name: Daily Software News Bot

on:
  schedule:
    - cron: '0 13 * * *'  # runs every day at 9 AM EST (13 UTC)
  workflow_dispatch:      # allows manual run

jobs:
  post-news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install feedparser requests

      - name: Run news bot
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          python3 news_bot.py
